apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- forms-secret-config.yaml
- forms-serviceaccount.yaml
# - forms-aws-secretmanager-appsettings.yaml
- forms-app.yaml
- forms-service.yaml
- forms-logging-flow.yaml
- forms-logging-opensearch.yaml
- forms-app-hpa.yaml
